language: python
sudo: required
python: 3.6

install:
    - sudo apt-get -y install python3-pyqt5
    - pip install -r dev-requirements.txt
    - pip install -r requirements.txt

script:
    - ./run_tests.sh

after_success:
    - codecov
